; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
PrivilegesRequired=none
AppId={{A398A267-E9C9-43C1-A95F-B4B00D6CAAFF}}
AppName=Solar Uncertainty Integrator

; 64-bit installer extensions - remove if an issue
;ArchitecturesAllowed=x86 x64 ia64
;ArchitecturesInstallIn64BitMode=x64 ia64

; 32-bit and 64-bit installer
; "ArchitecturesInstallIn64BitMode=x64" requests that the install be
; done in "64-bit mode" on x64, meaning it should use the native
; 64-bit Program Files directory and the 64-bit view of the registry.
; On all other architectures it will install in "32-bit mode".
ArchitecturesInstallIn64BitMode=x64
; Note: We don't set ProcessorsAllowed because we want this
; installation to run on all architectures (including Itanium,
; since it's capable of running 32-bit code too).



; UPDATE THESE TO MATCH THE VERSION
AppVerName=SUNI 2024.6.7
DefaultDirName={sd}\SUNI\2024.6.7

AppPublisher=National Renewable Energy Laboratory
AppPublisherURL=
AppSupportURL=
AppUpdatesURL=
DefaultGroupName=Solar Uncertainty Integrator
OutputDir=.
OutputBaseFilename=SUNI-install
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes
InfoBeforeFile=
UsePreviousAppDir=no
; do not use previous setup 
UsePreviousTasks=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]

;Source: "../../build/SUNI/Release/python/*"; DestDir: "{app}/python"; Excludes: ".svn,*.map"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "msvcp140.dll"; DestDir: "{app}/"; Excludes: ".svn,*.map";  Flags: ignoreversion recursesubdirs createallsubdirs
Source: "vcruntime140.dll"; DestDir: "{app}/"; Excludes: ".svn,*.map";  Flags: ignoreversion recursesubdirs createallsubdirs
Source: "vcruntime140_1.dll"; DestDir: "{app}/"; Excludes: ".svn,*.map";  Flags: ignoreversion recursesubdirs createallsubdirs
Source: "../../build/SUNI/Release/SUNI.exe"; DestDir: "{app}/"; Excludes: ".svn,*.map";  Flags: ignoreversion recursesubdirs createallsubdirs
Source: "Configuration Files/*"; DestDir: "{app}/Configuration Files"; Excludes: ".svn,*.map"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "Instrument Files/*"; DestDir: "{app}/Instrument Files"; Excludes: ".svn,*.map"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "System Files/*"; DestDir: "{app}/System Files"; Excludes: ".svn,*.map"; Flags: ignoreversion recursesubdirs createallsubdirs


; NOTE: Don't use "Flags: ignoreversion" on any shared system files
[Icons]
Name: "{group}\Solar Uncertainty Integrator"; Filename: "{app}\SUNI.exe"  ; Check: Is64BitInstallMode
Name: "{commondesktop}\Solar Uncertainty Integrator"; Filename: "{app}\SUNI.exe"; Tasks: desktopicon; Check: Is64BitInstallMode

[Registry]
Root: HKCR; Subkey: "Applications\SUNI.exe"; ValueType: none; ValueName: ; ValueData: SUNI; Flags: deletekey; Check: IsAdmin


[Run]
Filename: "{app}\SUNI.exe"; Flags: postinstall skipifsilent unchecked; Description: "{cm:LaunchProgram,Solar Uncertainty Integrator}"; Check: Is64BitInstallMode


[Code]



// 12/08/08 - added to select appropriate installation path that is writeable by the user
function IsRegularUser(): Boolean;
begin
  Result := not (IsAdmin or IsPowerUserLoggedOn);
end;

// 4/14/09 - modify to install in localappdata always - avoids UAC issue reported by Paul
function DefDirRoot(Param: String): String;
begin
//  if IsRegularUser then
    Result := ExpandConstant('{localappdata}')
//  else
//    Result := ExpandConstant('{pf}')
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Log('ShouldSkipPage(' + IntToStr(PageID) + ') called');
  { Skip wpInfoBefore page; show all others }
  case PageID of
    9:  // additional tasks SAM issue 942    
      begin
      if IsRegularUser then
        Result := True
      else
        Result := False;
      end
    else
      Result := False;
  end;
end;